# Generated by Django 5.0.1 on 2025-12-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="llm_provider",
            field=models.CharField(default="ollama", max_length=50),
        ),
        migrations.AlterField(
            model_name="agent",
            name="model",
            field=models.CharField(default="mistral:7b", max_length=100),
        ),
    ]
