# Generated by Django 5.0.1 on 2025-12-13 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether Meggy is actively monitoring and can proactively engage",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(default="Chat with Meggy", max_length=200),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
