# Generated by Django 5.0.1 on 2025-12-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_usermemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_proactive_message_at',
            field=models.DateTimeField(blank=True, help_text='When Meggy last initiated contact', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_user_message_at',
            field=models.DateTimeField(blank=True, help_text='When user last sent a message', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='proactive_responses_received',
            field=models.IntegerField(default=0, help_text='How many times user responded to proactive messages'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='proactivity_level',
            field=models.IntegerField(default=5, help_text='Proactivity level 1-10 (1=passive, 10=very proactive). Auto-adjusts based on user engagement.'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_proactive_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_user_messages',
            field=models.IntegerField(default=0),
        ),
    ]
