# Generated by Django 5.0.1 on 2025-12-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_last_proactive_message_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='auto_adjust_proactivity',
            field=models.BooleanField(default=True, help_text='User preference: Allow system to auto-adjust proactivity level based on engagement'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='max_proactivity_level',
            field=models.IntegerField(default=10, help_text='User preference: Maximum proactivity level (prevents auto-adjustment above this)'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='min_proactivity_level',
            field=models.IntegerField(default=1, help_text='User preference: Minimum proactivity level (prevents auto-adjustment below this)'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='proactive_messages_enabled',
            field=models.BooleanField(default=True, help_text='User preference: Enable/disable proactive messages entirely'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, help_text='User preference: End of quiet hours', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, help_text='User preference: Start of quiet hours (no proactive messages)', null=True),
        ),
    ]
