# Generated by Django 5.0.1 on 2025-12-14 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_auto_adjust_proactivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Description of what the timer is for', max_length=200)),
                ('duration_seconds', models.IntegerField(help_text='Total duration in seconds')),
                ('end_time', models.DateTimeField(help_text='When the timer will end')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_seconds', models.IntegerField(blank=True, help_text='Seconds remaining when paused', null=True)),
                ('three_minute_warning_sent', models.BooleanField(default=False)),
                ('completion_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='timers_user_id_356667_idx'), models.Index(fields=['end_time', 'status'], name='timers_end_tim_610047_idx')],
            },
        ),
    ]
